version: 3

dotenv:
  - .env

tasks:
  pg:
    deps: [pg-front, dev-server, watch-engine]
  # DOUBLE CHECK $PLAYGROUND_PATH BEFORE RUNNING
  pg-front:
    cmds:
      - cd $PLAYGROUND_PATH&&pwd&&npm run dev
  watch-engine:
    cmds:
      - chokidar ./npm-pkgs/lunas/src/engine/index.ts -c "cp ./npm-pkgs/lunas/src/engine/index.ts $PLAYGROUND_PATH/src/engine/index.ts" --initial
  dev-server:
    cmds:
      - LUNAS_TEST=1 RUST_BACKTRACE=1 cargo watch -x run --features playground
    dir: crates/lunas_dev_server
  build:
    cmds:
      - cd ./crates/lunas_compiler/ && wasm-pack build --target nodejs
      - cp ./crates/lunas_compiler/pkg/*.js ./npm-pkgs/lunas/src/wasm-compiler/
      - cp ./crates/lunas_compiler/pkg/*.ts ./npm-pkgs/lunas/src/wasm-compiler/
      - cp ./crates/lunas_compiler/pkg/*.wasm ./npm-pkgs/lunas/src/wasm-compiler/
      - cd ./npm-pkgs/lunas/ && npm run build
      - mkdir -p ./npm-pkgs/lunas/dist/types
      - cp ./npm-pkgs/lunas/src/types/* ./npm-pkgs/lunas/dist/types/
      - mkdir -p ./npm-pkgs/lunas/dist/wasm-compiler
      - cp -r ./npm-pkgs/lunas/src/wasm-compiler/* ./npm-pkgs/lunas/dist/wasm-compiler/
  build-web:
    cmds:
      - cd ./crates/lunas_compiler/ && wasm-pack build --target web --features playground
  test:
    cmds:
      - npm run test
    dir: ./test
  test-ci:
    pre:
      - build
    cmds:
      - npm run install
      - npm run test
    dir: ./test
