version: 3

dotenv:
  - .env

tasks:
  pg:
    deps: [pg-front, dev-server, watch-runtime]
  # DOUBLE CHECK $PLAYGROUND_PATH BEFORE RUNNING
  pg-front:
    cmds:
      - cd $PLAYGROUND_PATH&&pwd&&npm run dev
  watch-runtime:
    cmds:
      - chokidar ./npm-pkgs/livon/src/runtime/index.ts -c "cp ./npm-pkgs/livon/src/runtime/index.ts $PLAYGROUND_PATH/src/runtime/index.ts" --initial
  dev-server:
    cmds:
      - RUST_BACKTRACE=1 cargo watch -x run --features playground
    dir: crates/livon_dev_server
  build:
    cmds:
      - cd ./crates/livon_compiler/ && wasm-pack build --target nodejs
      - cp ./crates/livon_compiler/pkg/*.js ./npm-pkgs/livon/src/wasm-compiler/
      - cp ./crates/livon_compiler/pkg/*.ts ./npm-pkgs/livon/src/wasm-compiler/
      - cp ./crates/livon_compiler/pkg/*.wasm ./npm-pkgs/livon/src/wasm-compiler/
      - cd ./npm-pkgs/livon/ && npm run build
      - mkdir -p ./npm-pkgs/livon/dist/types
      - cp ./npm-pkgs/livon/src/types/* ./npm-pkgs/livon/dist/types/
      - mkdir -p ./npm-pkgs/livon/dist/wasm-compiler
      - cp -r ./npm-pkgs/livon/src/wasm-compiler/* ./npm-pkgs/livon/dist/wasm-compiler/
  build-web:
    cmds:
      - cd ./crates/livon_compiler/ && wasm-pack build --target web --features playground
