[package]
name = "livon_dev_server"
version = "0.0.1"
edition = "2021"

[dependencies]
livon_compiler = { version = "0.1.0", path = "../livon_compiler", features = [
  "playground",
] }
serde_json = "1.0.138"
tokio = { version = "1", features = ["full"] }
warp = "0.3"

[features]
playground = []
