name: Check package.json version

on:
  pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - beta

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check package.json version format
        run: |
          VERSION=$(cat ./npm-pkgs/lunas/package.json | jq -r '.version')
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+$ ]]; then
            echo "Version format is correct"
          else
            echo "Version format is incorrect" && exit 1
          fi
      - name: Create PR review on failure
        if: ${{ failure() }}
        run: |
          NEW_VERSION=$(cat ./npm-pkgs/lunas/package.json | jq -r '.version')
          gh pr comment ${{ github.event.pull_request.number }} --body "The version in package.json '$VERSION' does not adhere to beta version format.
          Please correct it."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create PR review on success
        if: ${{ success() }}
        run: |
          CURRENT_VERSION=$(npm show lunas@beta version)
          NEW_VERSION=$(cat ./npm-pkgs/lunas/package.json | jq -r '.version')
          gh pr comment ${{ github.event.pull_request.number }} --body "The version in package.json '$NEW_VERSION' adheres to the beta version format.
          Current version in npm is '$CURRENT_VERSION'."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
