name: Publish npm package

on:
  pull_request:
    branches:
      - beta
    types: [closed]
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build
        run: |
          task build
      - name: Log in to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish npm package
        run: |
          npm publish --tag beta
        working-directory: ./npm-pkgs/lunas
  generate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate Tag
        id: tag
        run: echo ::set-output name=tag::$(cat ./npm-pkgs/lunas/package.json | jq -r '.version')
      - name: Create Tag
        run: git tag ${{ steps.tag.outputs.tag }}
      - name: Push Tag
        run: git push origin ${{ steps.tag.outputs.tag }}
