name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Run Test
        run: |
          task test-ci
